### PR TITLE
Moves /tests to other folder so that unit tests also work

### PR DESCRIPTION
**Pull request by mkoistinen**
Attempted to get a coverage report by running `> ./coverage`, coverage reported no tests. Culprit is that this newer directory at the root of the repo is "shadowing" the real unit-tests folder at /aldryn_events/tests.

We need to move the frontend testing folder... preferably into the /aldryn_events/tests folder somewhere.

This PR is a temporary measure, but can be adapted for a more permanent configuration before committing.

### CODE REVIEW

**Comment by intellectronica** [comment]
I don't think this PR does what is advertised. Only change I see is codeclimate.yml

**Comment by FinalAngel** [comment]
@mkoistinen can't we just omit the folder using: http://nedbatchelder.com/code/coverage/source.html#source

```
omit = 
    *migrations*
    tests/*
```

**Comment by FinalAngel** [comment]
@mkoistinen this seems to do the trick or?

**Comment by mkoistinen** [comment]
@intellectronica dang, you're right. I must've gotten my commits crossed.

@FinalAngel No, this doesn't do the trick, sadly:

````
python runtests.py 
Creating test database for alias 'default'...

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
````

**Comment by mkoistinen** [comment]
@intellectronica This is what it was meant to be.

**Comment by intellectronica** [comment]
:+1:

**Pull request merged**
