### PR TITLE
Added unit test

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request adds unit test for "success" function**

Also:
- small line width fix

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM but also wait for @vxsx

**Comment by vxsx** [comment]
the linting failed but didn't show any errors on travis (which is something we need to actually fix)

**Comment by vxsx** [comment]
also pep8 failed in one of the cases, but that's something else /cc @cyberstar

**Comment by Marketionist** [comment]
I know what the linting error is - pinned it out locally. The fix is coming...

**Comment by vxsx** [comment]
@Marketionist build now correctly fails with linting error, ok to continue :)

**Comment by Marketionist** [comment]
Small fix added. Is it ok now @vxsx ?

**Comment by vxsx** [comment]
LGTM but wait for travis :D

**Pull request merged**
