### PR TITLE
Update documentations

### PR DESCRIPTION
**Pull request by FinalAngel**
- adapt to general docs
- remove unfinished sections
- adapt runtests.py

### CODE REVIEW

**Comment by intellectronica** [comment]
are you sure? i thought the original was fine and that test_settings is the django settings file to use in test.

**Comment by FinalAngel** [comment]
@intellectronica we don't have ``runtests.py`` in any of the addons ;) just alignment

**Comment by intellectronica** [comment]
ah i see that now. whatever, as long as it's consistent.

**Comment by FinalAngel** [comment]
waiting for @evildmp to have a look

**Comment by evildmp** [comment]
Looks good, but puzzled by the change to ``python test_settings.py``.

**Comment by intellectronica** [comment]
I have to say that I find that change a bit strange too. It is documented, so not really a problem, but I don't understand why that's a good thing to do.

**Comment by FinalAngel** [comment]
neither in aldryn-faq nor aldryn-newsblog do we have a ``runtests.py``. aldryn-events had a ``runtests.py`` which is legacy code. All addons use ``python test_settings.py`` @evildmp and @intellectronica

**Comment by evildmp** [comment]
All OK with me

**Comment by intellectronica** [comment]
:+1:

**Pull request merged**
