### PR TITLE
Add test and requirements

### PR DESCRIPTION
**Pull request by mkoistinen**

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1: but why have the tests not completed yet (it's been 12h)?

**Comment by evildmp** [comment]
@intellectronica @mkoistinen OK, I think this is failing because the ``docs/conf.py`` lacks the spelling extension that's in master.

**Comment by cyberstar** [comment]
rebased, + #172 without overhead

**Comment by mkoistinen** [comment]
LGTM, nice work!

**Comment by evildmp** [comment]
Looks good to me too, let's see what Travis has to say.

**Comment by evildmp** [comment]
OK, now it really is ready to merge with all tests passing. @mkoistinen  let's merge!

**Pull request merged**
