### PR TITLE
Fix plugins forms (#95), respect app configs, filter not published/apphooked configs

### PR DESCRIPTION
**Pull request by cyberstar**
Fix  issue #95.
This allows us to filter app configs correctly according to app config state and if it is app hooked check if page is published (for cases when aldryn-apphook-reload is not used on the project.
Also minor changes to templates to use get_title instead of unicode method, because then we can display handy app config information in forms, and still have control over title and translations.

Also should be applicable to #74.

### CODE REVIEW

**Comment by FinalAngel** [comment]
FE LGTM

**Comment by mkoistinen** [comment]
LGTM, but why are tests failing?

**Comment by cyberstar** [comment]
@mkoistinen seems that because of new code in init coverage has been decreased and that doesn't meet >=90% anymore...

**Comment by mkoistinen** [comment]
LGTM

**Pull request merged**
