### PR TITLE
Force the process to exit with error code if couldn't create the tunnel

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request updates gulpfile.js to force the process to exit with error code if couldn't create the Sauce Labs tunnel**

### CODE REVIEW

**Comment by Marketionist** [comment]
@FinalAngel @vxsx please review. I can't retrigger the build as I don't have access to see it on Travis.

**Comment by FinalAngel** [comment]
LGTM

**Comment by Marketionist** [comment]
@FinalAngel if it's ok, then please merge - I don't have rights to do it

**Comment by FinalAngel** [comment]
thank you @Marketionist

**Pull request merged**
