### PR TITLE
Removed extended_choices

### PR DESCRIPTION
**Pull request by FinalAngel**
Fixes an issue with the latest django-extended-choices release by removing the dependency. The error caused was:

```
[0m[91m File "/virtualenv/lib/python3.5/site-packages/aldryn_events/models.py", line 353, in <module> 
class Registration(models.Model): 
File "/virtualenv/lib/python3.5/site-packages/aldryn_events/models.py", line 369, in Registration 
[0m[91m _('Salutation'), max_length=5, choices=SALUTATIONS.CHOICES, 
AttributeError: 'Choices' object has no attribute 'CHOICES' 
[0m
```

### CODE REVIEW

**Comment by Chive** [comment]
-1, why remove ``extended-choices`` instead of fixing the actual bug?

**Comment by Chive** [comment]
@FinalAngel this should work fine

```python

SALUTATIONS = Choices(
    ('SALUTATION_FEMALE', 'mrs', ugettext('Ms.')),
    ('SALUTATION_MALE', 'mr', ugettext('Mr.')),
)
salutation = models.CharField(
    _('Salutation'), max_length=5, choices=SALUTATIONS,
    default=SALUTATIONS.SALUTATION_FEMALE,
)
```

**Comment by FinalAngel** [comment]
@Chive still need to figure out why @czpython PR is still open where its apparently adapted: https://github.com/aldryn/aldryn-events/pull/234

IMO extended-choices is only used there and we can very easily get rid of yet another dependency by quickly adapting the code.

**Comment by Chive** [comment]
@stefanfoulis have you seen the other PR #234

**Comment by FinalAngel** [comment]
@Chive while this might be the "super-simple" fix, you could also argue to pin the dependency to avoid future problems. Removing it altogether, if its only used in this simple instance, is cleaner IMO.

**Comment by stefanfoulis** [comment]
@Chive I had a quick look, yes. Does it work for both old and new versions of extended choices?

**Comment by Chive** [comment]
@stefanfoulis yes. ``.CHOICES`` has been "deprecated" in this version https://github.com/twidi/django-extended-choices/commit/fd35ba779aed3494aa08d5e9d9b34e969649fd8e released in May 2nd 2015

**Comment by FinalAngel** [comment]
closing in favour of https://github.com/aldryn/aldryn-events/issues/236

**Pull request closed without merging**
