### PR TITLE
Saucelabs integration

### PR DESCRIPTION
**Pull request by FinalAngel**
- add saucelabs connect

**TODO**
- [x] Change access to public djangocms repo

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1:

**Comment by mkoistinen** [comment]
Just a question, does this need to be touched in anyway now that we've merged #72?

**Comment by FinalAngel** [comment]
@mkoistinen we still need sauce to get up and running and some way to connect to integration tests

**Comment by mkoistinen** [comment]
Can this be merged?

**Comment by FinalAngel** [comment]
@mkoistinen yes as travis passes :)

**Pull request merged**
